BATTLE_AREA_WIDTH = 1200
BATTLE_AREA_HEIGHT = 380
NUM_COLS = 6
NUM_ROWS = 3
REC_WIDTH = 175
REC_HEIGHT = 100
SIDE_MARGIN = 25
TOP_MARGIN = 25

ACTION_AREA_HEIGHT = 150
ACTION_TOP_MARGIN = 15
ACTION_SIDE_MARGIN = 15
ACTION_HEIGHT = ACTION_AREA_HEIGHT - (2*ACTION_TOP_MARGIN)
ACTION_WIDTH = 150

SIDEBAR_HEIGHT = BATTLE_AREA_HEIGHT + ACTION_AREA_HEIGHT
SIDEBAR_WIDTH = 175

EXECUTE_HEIGHT = 75

def calc_inter_margin( total_length, end_margins, num_spaces, space_width ):
	return ( total_length - ( 2 * end_margins ) - ( num_spaces * space_width ) ) / ( num_spaces - 1 )

INTER_HORIZ_MARGIN = calc_inter_margin( BATTLE_AREA_WIDTH, SIDE_MARGIN, NUM_COLS, REC_WIDTH )
INTER_VERT_MARGIN = calc_inter_margin( BATTLE_AREA_HEIGHT, TOP_MARGIN, NUM_ROWS, REC_HEIGHT )

EXECUTE_ICON_PATH = "assets/execute4.png"
